name: Dynamic Matrix Build

on: [push, pull_request]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate matrix dynamically
        id: generate-matrix
        run: |
          echo "matrix={\"os\":[\"ubuntu-latest\",\"windows-latest\"],\"node\":[\"12\",\"14\"]}" >> $GITHUB_OUTPUT

  echo-matrix:
    needs: generate-matrix
    runs-on: ubuntu-latest
    steps:
      - name: echo matrix
        run: |
          echo ${{ needs.generate-matrix.outputs.matrix }}

  dynamic-matrix-build:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run build
        run: |
          echo "Running build for OS: ${{ matrix.os }} and version: ${{ matrix.version }}"
